# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carriers',
            fields=[
                ('carrier_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('scac_mc', models.CharField(max_length=12)),
                ('carrier_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MP_Load',
            fields=[
                ('number', models.CharField(max_length=24)),
                ('track_start_date_time', models.DateTimeField()),
                ('track_start_date_time_TZ', models.CharField(choices=[('ET', 'Eastern Standard Time'), ('CT', 'Central Standard Time'), ('AZ', 'Arizona'), ('MT', 'Mountain Time'), ('PT', 'Pacific Standard Time'), ('AK', 'Alaska'), ('HI', 'Hawaii')], max_length=2)),
                ('track_duration_hours', models.IntegerField()),
                ('track_interval_minutes', models.IntegerField()),
                ('partner_mpid', models.IntegerField()),
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier_name', models.TextField()),
                ('carrier_id', models.CharField(max_length=24)),
                ('last_stop_event_completed', models.CharField(max_length=64)),
                ('stop_id', models.CharField(max_length=12)),
                ('stop_type', models.CharField(choices=[('PU', 'Pick Up'), ('DO', 'Drop Off')], max_length=2)),
                ('start_date_time', models.DateTimeField()),
                ('start_date_time_TZ', models.CharField(choices=[('ET', 'Eastern Standard Time'), ('CT', 'Central Standard Time'), ('AZ', 'Arizona'), ('MT', 'Mountain Time'), ('PT', 'Pacific Standard Time'), ('AK', 'Alaska'), ('HI', 'Hawaii')], max_length=2)),
                ('end_date_time', models.DateTimeField()),
                ('end_date_time_TZ', models.CharField(choices=[('ET', 'Eastern Standard Time'), ('CT', 'Central Standard Time'), ('AZ', 'Arizona'), ('MT', 'Mountain Time'), ('PT', 'Pacific Standard Time'), ('AK', 'Alaska'), ('HI', 'Hawaii')], max_length=2)),
                ('stop_notes', models.TextField()),
                ('email_updates_to', models.CharField(max_length=64)),
                ('load_notes', models.TextField()),
                ('order_id_MP', models.CharField(max_length=32)),
                ('order_status_MP', models.CharField(max_length=64)),
                ('order_error_code_MP', models.IntegerField()),
                ('order_error_message_MP', models.TextField()),
                ('order_rev_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='truck_stop',
            fields=[
                ('stop_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stop_latitude', models.FloatField()),
                ('stop_longitude', models.FloatField()),
                ('stop_address_line1', models.CharField(max_length=64)),
                ('stop_address_line2', models.CharField(max_length=64)),
                ('stop_city', models.CharField(max_length=64)),
                ('stop_state_or_province', models.CharField(max_length=64)),
                ('stop_postal_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='mp_load',
            name='stop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.truck_stop'),
        ),
    ]
