# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carriers',
            fields=[
                ('carrier_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('scac_mc', models.CharField(max_length=12)),
                ('carrier_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='mp_Load',
            fields=[
                ('number', models.CharField(blank=True, default='', max_length=24)),
                ('track_start_date_time', models.DateTimeField()),
                ('track_start_date_time_TZ', models.CharField(blank=True, choices=[('ET', 'Eastern Standard Time'), ('CT', 'Central Standard Time'), ('AZ', 'Arizona'), ('MT', 'Mountain Time'), ('PT', 'Pacific Standard Time'), ('AK', 'Alaska'), ('HI', 'Hawaii')], default='', max_length=2)),
                ('track_duration_hours', models.IntegerField()),
                ('track_interval_minutes', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='notify_on_event_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=12)),
                ('event_code', models.CharField(max_length=6)),
                ('event_time_utc', models.DateTimeField()),
                ('event_time_local', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street1', models.CharField(max_length=64)),
                ('street2', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('postal', models.IntegerField()),
                ('country', models.CharField(max_length=128)),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load')),
            ],
        ),
        migrations.CreateModel(
            name='notify_on_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('uncertainty', models.IntegerField()),
                ('street1', models.CharField(max_length=64)),
                ('street2', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('postal', models.IntegerField()),
                ('country', models.CharField(max_length=128)),
                ('location_time_utc', models.DateTimeField()),
                ('location_time_local', models.DateTimeField()),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load')),
            ],
        ),
        migrations.CreateModel(
            name='notify_on_order_status_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('status_message', models.TextField()),
                ('status_time_stamp', models.DateTimeField()),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load')),
            ],
        ),
        migrations.CreateModel(
            name='notify_on_schedule_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('PU', 'Pick Up'), ('DO', 'Drop Off')], max_length=2)),
                ('stop_id', models.CharField(max_length=12)),
                ('address_line1', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('postal', models.CharField(max_length=16)),
                ('alert_code', models.IntegerField()),
                ('schedule_time_begin_local', models.DateTimeField()),
                ('schedule_time_end_local', models.DateTimeField()),
                ('location_time_utc', models.DateTimeField()),
                ('schedule_alert_text', models.TextField()),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load')),
            ],
        ),
        migrations.CreateModel(
            name='truck_stop',
            fields=[
                ('stop_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stop_latitude', models.FloatField()),
                ('stop_longitude', models.FloatField()),
                ('stop_address_line1', models.CharField(max_length=64)),
                ('stop_address_line2', models.CharField(blank=True, default='', max_length=64)),
                ('stop_city', models.CharField(max_length=64)),
                ('stop_state_or_province', models.CharField(max_length=64)),
                ('stop_postal_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='notify_on_schedule_alert',
            name='stop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.truck_stop'),
        ),
        migrations.AddField(
            model_name='notify_on_event_update',
            name='stop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.truck_stop'),
        ),
    ]
