# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_on_order_status_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='carrier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.carriers'),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_id_MP',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='notify_on_order_status_change',
            name='order_id_MP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.MP_Load'),
        ),
    ]
