# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0002_auto_20170920_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify_on_order_status_change',
            name='order_id_MP',
        ),
        migrations.DeleteModel(
            name='notify_on_order_status_change',
        ),
    ]
