# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0006_auto_20170923_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_status_change',
            new_name='notify_order_status_change',
        ),
    ]
