# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0007_auto_20170923_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_on_order_status_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('status_message', models.TextField()),
                ('status_time_stamp', models.DateTimeField()),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.MP_Load')),
            ],
        ),
        migrations.RemoveField(
            model_name='notify_order_status_change',
            name='order_id_number',
        ),
        migrations.DeleteModel(
            name='notify_order_status_change',
        ),
    ]
