# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0009_notify_on_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_on_event_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=12)),
                ('event_code', models.CharField(max_length=6)),
                ('event_time_utc', models.DateTimeField()),
                ('event_time_local', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street1', models.CharField(max_length=64)),
                ('street2', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('postal', models.IntegerField()),
                ('country', models.CharField(max_length=128)),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.MP_Load')),
                ('stop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.truck_stop')),
            ],
        ),
    ]
