# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0010_notify_on_event_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_on_schedule_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('PU', 'Pick Up'), ('DO', 'Drop Off')], max_length=2)),
                ('stop_id', models.CharField(max_length=12)),
                ('stop_address_line1', models.CharField(max_length=64)),
                ('stop_city', models.CharField(max_length=64)),
                ('stop_state_or_province', models.CharField(max_length=64)),
                ('stop_postal_code', models.CharField(max_length=16)),
                ('schedule_alert_code', models.IntegerField()),
                ('schedule_time_begin_local', models.DateTimeField()),
                ('schedule_time_end_local', models.DateTimeField()),
                ('location_time_utc', models.DateTimeField()),
                ('schedule_alert_text', models.TextField()),
                ('order_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.MP_Load')),
                ('stop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.truck_stop')),
            ],
        ),
    ]
