# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0011_notify_on_schedule_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp_load',
            old_name='partner_mpid',
            new_name='partner_id',
        ),
        migrations.AlterField(
            model_name='notify_on_event_update',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_location',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_order_status_change',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_schedule_alert',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
    ]
