# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0012_auto_20170924_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify_on_schedule_alert',
            old_name='stop_address_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='notify_on_schedule_alert',
            old_name='schedule_alert_code',
            new_name='alert_code',
        ),
        migrations.RenameField(
            model_name='notify_on_schedule_alert',
            old_name='stop_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='notify_on_schedule_alert',
            old_name='stop_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='notify_on_schedule_alert',
            old_name='stop_state_or_province',
            new_name='state_or_province',
        ),
        migrations.AlterField(
            model_name='notify_on_event_update',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_location',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_order_status_change',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_schedule_alert',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
    ]
