# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0015_auto_20171002_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp_load',
            name='email_updates_to',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='last_stop_event_completed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='load_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_error_code_MP',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_error_message_MP',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_id_MP',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_rev_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='order_status_MP',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='stop_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notify_on_event_update',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_location',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_order_status_change',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_schedule_alert',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='truck_stop',
            name='stop_address_line2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
