# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_test_app', '0017_auto_20171002_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp_load',
            name='carrier_id',
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='carrier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.carriers'),
        ),
        migrations.AlterField(
            model_name='mp_load',
            name='last_stop_event_completed',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notify_on_event_update',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_location',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_order_status_change',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
        migrations.AlterField(
            model_name='notify_on_schedule_alert',
            name='order_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_test_app.mp_Load'),
        ),
    ]
